# Generated by Django 3.1.5 on 2021-02-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='washapp/no_image.svg', upload_to='washapp/employees/'),
        ),
    ]
