# Generated by Django 3.1.5 on 2021-02-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210216_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Customer'), (2, 'Employee')], default=1),
            preserve_default=False,
        ),
    ]
