# Generated by Django 3.1.5 on 2021-02-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('employee', 'Employee')], max_length=100, null=True),
        ),
    ]
