# Generated by Django 3.1.5 on 2021-02-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210218_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('employee', 'Employee'), ('employer', 'Employer')], max_length=100, null=True),
        ),
    ]
