# Generated by Django 3.1.5 on 2021-01-29 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoothToCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarWashBooth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupied', models.BooleanField(blank=True)),
                ('car', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='washapp.car')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('booths', models.ManyToManyField(related_name='booths', through='washapp.BoothToCompany', to='washapp.CarWashBooth')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Hired')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('requested', models.DateTimeField()),
                ('completed', models.DateTimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='washapp.car')),
                ('wash_booth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='washapp.carwashbooth')),
                ('washer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washapp.employee')),
            ],
            options={
                'unique_together': {('washer', 'wash_booth', 'requested', 'car')},
            },
        ),
        migrations.CreateModel(
            name='OrderToCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='washapp.company')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='washapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeToCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='washapp.company')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='washapp.employee')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(through='washapp.EmployeeToCompany', to='washapp.Employee'),
        ),
        migrations.AddField(
            model_name='company',
            name='orders',
            field=models.ManyToManyField(through='washapp.OrderToCompany', to='washapp.Order'),
        ),
        migrations.AddField(
            model_name='carwashbooth',
            name='occupant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='washapp.employee'),
        ),
        migrations.AddField(
            model_name='boothtocompany',
            name='booth',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='washapp.carwashbooth'),
        ),
        migrations.AddField(
            model_name='boothtocompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='washapp.company'),
        ),
    ]
