# Generated by Django 3.1.5 on 2021-02-15 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(default='washapp/no_image.svg', upload_to='washapp/employees/')),
                ('share', models.PositiveSmallIntegerField(default=45)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Hired')),
            ],
        ),
        migrations.CreateModel(
            name='CarWashBooth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupied', models.BooleanField(blank=True)),
                ('car', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='washapp.car')),
                ('occupant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='washapp.employee')),
            ],
            options={
                'verbose_name': 'Booth',
                'verbose_name_plural': 'Booths',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=100)),
                ('requested', models.DateTimeField()),
                ('completed', models.DateTimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='washapp.car')),
                ('wash_booth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='washapp.carwashbooth')),
                ('washer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washapp.employee')),
            ],
            options={
                'unique_together': {('washer', 'wash_booth', 'requested', 'car')},
            },
        ),
    ]
