# Generated by Django 3.1.5 on 2021-01-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterField(
            model_name='role',
            name='salary',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
