# Generated by Django 3.1.5 on 2021-01-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washapp', '0002_auto_20210129_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boothtocompany',
            options={'verbose_name': 'Booth', 'verbose_name_plural': 'Booths'},
        ),
        migrations.AlterModelOptions(
            name='employeetocompany',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='ordertocompany',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
