# Generated by Django 3.1.5 on 2021-01-22 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('washapp', '0002_auto_20210123_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='washapp.role'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='salary',
            field=models.PositiveSmallIntegerField(verbose_name='Salary / Monthly'),
        ),
    ]
