# Generated by Django 3.1.5 on 2021-02-18 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('washapp', '0003_auto_20210216_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
