# Generated by Django 3.1.5 on 2021-01-30 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('washapp', '0003_auto_20210129_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='booths',
        ),
        migrations.RemoveField(
            model_name='company',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='company',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='employeetocompany',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employeetocompany',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='ordertocompany',
            name='company',
        ),
        migrations.RemoveField(
            model_name='ordertocompany',
            name='order',
        ),
        migrations.DeleteModel(
            name='BoothToCompany',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='EmployeeToCompany',
        ),
        migrations.DeleteModel(
            name='OrderToCompany',
        ),
    ]
