# Generated by Django 3.1.5 on 2021-01-22 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('washapp', '0003_auto_20210123_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='hired_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Hired'),
            preserve_default=False,
        ),
    ]
