# Generated by Django 3.1.5 on 2021-01-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washapp', '0004_auto_20210131_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
