# Generated by Django 3.1.5 on 2021-02-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washapp', '0004_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
