# Generated by Django 3.1.5 on 2021-01-22 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('washapp', '0004_auto_20210123_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added to DB'),
        ),
        migrations.CreateModel(
            name='CarWashBooth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupied', models.BooleanField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='washapp.car')),
                ('occupant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='washapp.employee')),
            ],
        ),
    ]
