# Generated by Django 3.1.5 on 2021-01-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washapp', '0005_auto_20210131_0257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carwashbooth',
            options={'verbose_name': 'Booth', 'verbose_name_plural': 'Booths'},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='full_name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='halson', max_length=100),
            preserve_default=False,
        ),
    ]
