# Generated by Django 3.1.5 on 2021-01-23 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('washapp', '0006_auto_20210123_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashbooth',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='washapp.car'),
        ),
        migrations.AlterField(
            model_name='carwashbooth',
            name='occupied',
            field=models.BooleanField(blank=True),
        ),
    ]
