# Generated by Django 3.1.5 on 2021-01-23 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('washapp', '0007_auto_20210123_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashbooth',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='washapp.car', unique=True),
        ),
        migrations.AlterField(
            model_name='carwashbooth',
            name='occupant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='washapp.employee', unique=True),
        ),
    ]
