# Generated by Django 3.1.5 on 2021-02-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washapp', '0007_employee_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
    ]
