# Generated by Django 3.1.5 on 2021-02-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washapp', '0008_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(default='washapp/no_image.svg', upload_to='washapp/employees'),
        ),
    ]
