# Generated by Django 3.1.5 on 2021-01-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washapp', '0008_auto_20210123_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
