# Generated by Django 3.1.5 on 2021-01-23 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('washapp', '0009_auto_20210123_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashbooth',
            name='car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='washapp.car'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='washapp.role'),
        ),
    ]
