# Generated by Django 3.1.5 on 2021-02-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washapp', '0009_employee_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(default='washapp/no_image.svg', upload_to='washapp/employees/'),
        ),
    ]
