# Generated by Django 3.1.5 on 2021-01-23 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('washapp', '0010_auto_20210123_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashbooth',
            name='occupant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='washapp.employee'),
        ),
    ]
